### PR TITLE
Use keyword-args

### PR DESCRIPTION
**Pull request by bezoar17**
### Contributor Self-Check:

* [x] My commits and messages [are solid](https://chris.beams.io/posts/git-commit/)
* [x] I have included tests that check success and failure
* [x] I have updated the README as appropriate

### Which GitHub Issues does this PR address?

None

### What does this PR do?

Clean up the gem's API to use keyword arguments for read requests.

### How do I manually test this?

The test cases have been updated acc to the changes.

### CODE REVIEW

**Comment by bezoar17** [comment]
@danielpowell4 , please have a look at this PR. Don't know if any changes are needed for the specific functions like `create_customer` , `create_employee` etc.  I only use read request so haven't really gone through specific create, update flows. Also as this will be a breaking change, let me know what is needed from my side to ensure smooth release.

**Comment by danielpowell4** [comment]
@bezoar17 Thanks for this!

My first impression is that this is good to go. I am going to need a bit of time to dive in and make sure I'm 1000% confident in terms of how it looks and interacts with the rest of the gem.

Will report back when possible

**Comment by bezoar17** [comment]
Cool, no hurries. This will be a breaking and possibly big change.

**Comment by danielpowell4** [comment]
@bezoar17 Spoke to @jzornow and confirmed that this looking :+1: 

Much of the seeming "create" code supported Intacct's DTD 2.1 syntax is actually dead now

I want to run a few tests and do some cleanup later on this week but think it will likely be good to go

**Pull request merged**
